### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sourcemod#2]
Update this repo related with SM 1.12 ?

**Comment by maximee-leroyy** [comment]
Any reason behind this ?

**Comment by maximee-leroyy** [comment]
i want to get rid of this sourcemod fork and follow the upstream but there are some things that needs to be changed first:
- FullUpdate uses https://github.com/srcdslab/sourcemod/commit/05d673f0d6e69a4f6dc45bca85cb5d4213657bfc, discussed in https://github.com/srcdslab/sm-plugin-FullUpdate/issues/1 -> DONE
- All plugins uses https://github.com/srcdslab/sourcemod/commit/1730d4bd7f9904d33ece681aa1f293449a090d28, discussed in https://github.com/alliedmodders/sourcemod/pull/1069 -> NOT THAT IMPORTANT

**Comment by Rushaway** [comment]
> Any reason behind this ?

Entity Lumps feature can be usefull.

**Comment by maximee-leroyy** [comment]
> > Any reason behind this ?
> 
> Entity Lumps feature can be usefull.

okay yeah i saw something about this topic seems nice

**Comment by Rushaway** [comment]
Bump.
With entity lumps we can use striper source pawn instead of source.

**Comment by maximee-leroyy** [comment]
you can start to use upstream sourcemod as i have removed all dependencies from the sourcemod fork (except the ambiguous menu part)

**Comment by maximee-leroyy** [comment]
gonna stick with 1.11-dev since entity limps have been merged in 1.11-dev
